"""PaperScout email construction and delivery.

Constructs HTML email digests from scored papers and sends via SMTP.
Part of the hybrid notification approach (email + events).
"""

from __future__ import annotations

import logging
import math
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import TYPE_CHECKING

from soothe_community.paperscout.models import EmailContent, ScoredPaper

if TYPE_CHECKING:
    from soothe_community.paperscout.state import SmtpConfig

logger = logging.getLogger(__name__)

EMAIL_TEMPLATE = """
<!DOCTYPE HTML>
<html>
<head>
  <style>
    .star-wrapper {{
      font-size: 1.3em;
      line-height: 1;
      display: inline-flex;
      align-items: center;
    }}
    .half-star {{
      display: inline-block;
      width: 0.5em;
      overflow: hidden;
      white-space: nowrap;
      vertical-align: middle;
    }}
    .full-star {{
      vertical-align: middle;
    }}
  </style>
</head>
<body>

<div>
    {content}
</div>

<br><br>
<div>
    <p>This digest was generated by <strong>PaperScout</strong> for Soothe.</p>
    <p>To unsubscribe, disable the paperscout subagent in your configuration.</p>
</div>

</body>
</html>
"""


def get_stars_html(score: float) -> str:
    """Generate star rating HTML based on score.

    Args:
        score: Relevance score (0-10).

    Returns:
        HTML string with star rating.
    """
    full_star = '<span class="full-star">⭐</span>'
    half_star = '<span class="half-star">⭐</span>'

    low = 6
    high = 8

    if score <= low:
        return ""
    if score >= high:
        return full_star * 5

    interval = (high - low) / 10
    star_num = math.ceil((score - low) / interval)
    full_star_num = int(star_num / 2)
    half_star_num = star_num - full_star_num * 2
    return '<div class="star-wrapper">' + full_star * full_star_num + half_star * half_star_num + "</div>"


def create_paper_html(paper: ScoredPaper) -> str:
    """Create HTML block for a single paper.

    Args:
        paper: ScoredPaper to format.

    Returns:
        HTML string for the paper.
    """
    stars_html = get_stars_html(paper.score)

    # Format authors
    authors = paper.paper.authors[:5]
    authors_str = ", ".join(authors)
    if len(paper.paper.authors) > 5:
        authors_str += ", ..."

    # Format affiliations
    if paper.paper.affiliations:
        affiliations = paper.paper.affiliations[:5]
        affiliations_str = ", ".join(affiliations)
        if len(paper.paper.affiliations) > 5:
            affiliations_str += ", ..."
    else:
        affiliations_str = "Unknown Affiliation"

    # Code link
    code_link = ""
    if paper.paper.code_url:
        code_link = f'<a href="{paper.paper.code_url}" style="display: inline-block; text-decoration: none; font-size: 14px; font-weight: bold; color: #fff; background-color: #5bc0de; padding: 8px 16px; border-radius: 4px; margin-left: 8px;">Code</a>'

    return f"""
    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="font-family: Arial, sans-serif; border: 1px solid #ddd; border-radius: 8px; padding: 16px; background-color: #f9f9f9;">
    <tr>
        <td style="font-size: 20px; font-weight: bold; color: #333;">
            {paper.paper.title}
        </td>
    </tr>
    <tr>
        <td style="font-size: 14px; color: #666; padding: 8px 0;">
            {authors_str}
            <br>
            <br>
            <i>{affiliations_str}</i>
        </td>
    </tr>
    <tr>
        <td style="font-size: 14px; color: #333; padding: 8px 0;">
            <strong>Relevance:</strong> {stars_html}
        </td>
    </tr>
    <tr>
        <td style="font-size: 14px; color: #333; padding: 8px 0;">
            <strong>arXiv ID:</strong> {paper.paper.arxiv_id}
        </td>
    </tr>
    <tr>
        <td style="font-size: 14px; color: #333; padding: 8px 0;">
            <strong>TLDR:</strong> {paper.paper.tldr or "No summary available"}
        </td>
    </tr>
    <tr>
        <td style="padding: 8px 0;">
            <a href="{paper.paper.pdf_url}" style="display: inline-block; text-decoration: none; font-size: 14px; font-weight: bold; color: #fff; background-color: #d9534f; padding: 8px 16px; border-radius: 4px;">PDF</a>
            {code_link}
        </td>
    </tr>
    </table>
    """


def create_empty_email_html() -> str:
    """Create HTML for empty email (no papers found)."""
    return """
    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="font-family: Arial, sans-serif; border: 1px solid #ddd; border-radius: 8px; padding: 16px; background-color: #f9f9f9;">
    <tr>
        <td style="font-size: 20px; font-weight: bold; color: #333;">
            No Papers Today. Take a Rest!
        </td>
    </tr>
    </table>
    """


def _get_digest_date(papers: list[ScoredPaper]) -> str:
    """Get the digest date from papers or current date.

    Args:
        papers: List of scored papers.

    Returns:
        Date string in YYYY/MM/DD format.
    """
    if papers:
        # Get the latest published date from papers
        dates = [p.paper.published_date for p in papers if p.paper.published_date]
        if dates:
            latest_date = max(dates)
            return latest_date.strftime("%Y/%m/%d")

    # Fallback to current date
    return datetime.now().strftime("%Y/%m/%d")


def construct_email_content(papers: list[ScoredPaper]) -> EmailContent:
    """Construct complete email content from scored papers.

    Args:
        papers: List of scored papers to include.

    Returns:
        EmailContent object with subject, HTML body, and papers.
    """
    digest_date = _get_digest_date(papers)

    if not papers:
        content = create_empty_email_html()
        return EmailContent(
            subject=f"PaperScout Digest {digest_date} - No Papers Today",
            html_body=EMAIL_TEMPLATE.format(content=content),
            papers=[],
        )

    paper_blocks = [create_paper_html(paper) for paper in papers]
    content = "<br>".join(paper_blocks)

    return EmailContent(
        subject=f"PaperScout Digest {digest_date}",
        html_body=EMAIL_TEMPLATE.format(content=content),
        papers=[p.paper for p in papers],
    )


def send_email(
    email_content: EmailContent,
    smtp_config: SmtpConfig,
    recipient: str | None = None,
) -> bool:
    """Send email via SMTP.

    Args:
        email_content: Email content to send.
        smtp_config: SMTP server configuration.
        recipient: Email recipient (defaults to SMTP user).

    Returns:
        True if email sent successfully, False otherwise.
    """
    recipient = recipient or smtp_config.user

    try:
        # Create message
        msg = MIMEMultipart("alternative")
        msg["Subject"] = email_content.subject
        msg["From"] = smtp_config.user
        msg["To"] = recipient

        # Attach HTML body
        html_part = MIMEText(email_content.html_body, "html")
        msg.attach(html_part)

        # Attach text body if available
        if email_content.text_body:
            text_part = MIMEText(email_content.text_body, "plain")
            msg.attach(text_part)

        # Connect and send
        logger.info(f"Connecting to SMTP server: {smtp_config.host}:{smtp_config.port}")
        with smtplib.SMTP(smtp_config.host, smtp_config.port) as server:
            if smtp_config.use_tls:
                server.starttls()
            server.login(smtp_config.user, smtp_config.password)
            server.sendmail(smtp_config.user, recipient, msg.as_string())

        logger.info(f"Email sent successfully to {recipient}")
        return True

    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False


__all__ = [
    "construct_email_content",
    "create_empty_email_html",
    "create_paper_html",
    "get_stars_html",
    "send_email",
]
